### ISSUE TITLE
MethodOfLines complains about my model...

### ISSUE THREAD

**Issue by B-LIE** [SciML/MethodOfLines.jl#249]
Here is my model:
<img width="681" alt="image" src="https://user-images.githubusercontent.com/54220415/223722559-8ec832e0-0a10-4894-80d7-be469e45298b.png">

This 1D model describes the flow of ideal gas in a pipe. I assume that inlet pressure $p_0$ is a known function of time, and that the outlet mass flow rate $\dot{m}_L$ is a known function of time.

I get a few `warnings` after the statement:
```julia
@named pipe = PDESystem(eqs,bcs,doms,[t,x],[p(t,x), ṁ(t,x)], 
                    [RdM=>RdM0, T=>T0, A_p=>Ap0, g=>g0, H=>H0, L=>L0, ℘=>℘0, f=>f0])
```
but the code still runs. However, when I then do:
```julia
prob = discretize(pipe,disc);
```
I get more warnings, and eventually the running crashes.

**Question**: Is there a problem with the term: 

<img width="66" alt="image" src="https://user-images.githubusercontent.com/54220415/223723852-e4f2eb82-2455-4b39-8b1c-7d47dc7af724.png">

?? Is only the differentiation of a simple function allowed?

If so, how do I get around it?
* Differentiating out, or
* Adding an algebraic definition of the argument of the differentiation?

If you guys need it, I can provide the entire code.

**Comment by B-LIE** [comment]
In case you are interested in my code [note! I have successfully solved at least 3 PDEs using MethodsOfLine.jl, so I have a little experience with it]:

```julia
# PACKAGES
using ModelingToolkit
using DifferentialEquations
using Plots, LaTeXStrings
using MethodOfLines, DomainSets

# MODEL
parameters RdM T A_p g H L ℘ f 
@variables t x p(..) ṁ(..) # p_0(t) ṁ_L(t)
Dt = Differential(t)
Dx = Differential(x)
#
eqs = [Dt(p(t,x)) ~ -(RdM*T)/(A_p)*Dx(ṁ(t,x)),
        Dt(ṁ(t,x)) ~ -(RdM*T)/(A_p)*Dx((ṁ(t,x))^2/p(t,x)) - A_p*Dx(p(t,x)) +
                (g*H)/L*A_p/(RdM*T)*p(t,x) - RdM*T*℘/A_p^2/2*f*(ṁ(t,x))^2/p(t,x)]

#=  In case term needs to be expanded out:
eqs = [Dt(p(t,x)) ~ -(RdM*T)/(A_p)*Dx(ṁ(t,x)),
        Dt(ṁ(t,x)) ~ -(RdM*T)/(A_p)*( 2*ṁ(t,x)/p(t,x)*Dx(ṁ(t,x)) - (ṁ(t,x))^2/p(t,x)*Dx(p(t,x)) ) - A_p*Dx(p(t,x)) +
                (g*H)/L*A_p/(RdM*T)*p(t,x) - RdM*T*℘/A_p^2/2*f*(ṁ(t,x))^2/p(t,x)]
=#

# NUMERIC VALUES
# From A. Carlson and B. Lie, 1992
D0 = 1.422 # m 
Ap0 =pi*D0^2/4
℘0 = pi*D0
L0 = 122e3 # m 
RdM0 = 493 # J/(kg.K)
T0 = 12 + 273.15 # K
f0 = 0.28e-3 # friction factor
g0 = 9.81
H0 = 0
p0 = 8.4e6 # Pa
ṁ0 = 1.5e6/3600 # kg/s

# BOUNDARY FUNCTIONS
@register_symbolic p_0(t)
@register_symbolic ṁ_L(t)

p_0(t) = p0
ṁ_L(t) = ṁ0

# DOMAINS
L = L0
doms = [t ∈ Interval(0.0, 30*3600), x ∈ Interval(0, L)]

# (INITIAL &) BOUNDARY CONDITIONS
bcs = [ p(0,x) ~ p0,
        ṁ(0,x) ~ ṁ0,
        p(t,0) ~ p_0(t),
        ṁ(t,L) ~ ṁ_L(t)]

# SYMBOLIC MODEL
@named pipe = PDESystem(eqs,bcs,doms,[t,x],[p(t,x), ṁ(t,x)], 
                    [RdM=>RdM0, T=>T0, A_p=>Ap0, g=>g0, H=>H0, L=>L0, ℘=>℘0, f=>f0])

# The above leads to warnings, but nothing that stops the execution

# DISCRETIZATION INTO NUMERIC MODEL
Nmol = 10
order = 2 
disc = MOLFiniteDifference([x=>Nmol], t, approx_order=order)

prob = discretize(pipe,disc)

# The above `discretize` function runs for 1 minute ++ on my 12th gen intel laptop, then crashes

# SOLVING MODEL AND EXTRACTING RESULTS
sol = solve(prob)

solp = sol[p(t,x)]
solṁ = sol[ṁ(t,x)]
solx = sol[x]
solt = sol[t]

# Code crashes before this headline
```

**Comment by B-LIE** [comment]
Hm... I also tried with the following re-formulation (the model is the simplified Euler equations, i.e., without energy balance):

<img width="326" alt="image" src="https://user-images.githubusercontent.com/54220415/223976422-9be41291-d915-48eb-93cf-b2042a39b9ad.png">

This model avoids division by some variables, at least in the PDEs themselves (but shifting those operations to the algebraic constraints). And also makes sure that the differentiation operators are used on simple functions (instead of expressions). In this update, I have corrected a tiny non-physicality of the previous model to ensure that friction opposes flow also when the flow direction changes.

Anyways, I get the same error message with these equations.

**Comment by xtalax** [comment]
I think that the `Dx((ṁ(t,x))^2` is causing problems with the rule application, what error are you getting? In any case, try giving the discretization `advection_scheme = WENOScheme()`.

**Comment by xtalax** [comment]
Ok this is a bug, sorry about this. I will investigate closer soon.

**Comment by bgctw** [comment]
I am also fighting with a similar bug using ModelingToolkit 0.11.1 and 0.11.2. Would it be helpful to contribute another example where it occurs?

```
ERROR: MethodError: no method matching hasmetadata(::Pair{Num, Float64}, ::Type{Symbolics.VariableDefaultValue})
...
Stacktrace:
 [1] hasdefault(v::Pair{Num, Float64})
   @ ModelingToolkit ~/scratch/twutz/julia_cluster_depots/packages/ModelingToolkit/GJiqn/src/utils.jl:237
 [2] collect_defaults!(defs::Any, vars::Any)
   @ ModelingToolkit ~/scratch/twutz/julia_cluster_depots/packages/ModelingToolkit/GJiqn/src/utils.jl:255 [inlined]
 [3] process_variables!(var_to_name::Dict{Any, Any}, defs::Dict{Any, Any}, vars::Vector{Pair{Num, Float64}})
   @ ModelingToolkit ~/scratch/twutz/julia_cluster_depots/packages/ModelingToolkit/GJiqn/src/utils.jl:248
...
```

**Comment by bgctw** [comment]
Indeed, corrected to MethodOfLines 0.11.1 and 0.11.2. I cannot try 0.11.0 because it does not resolve due other (Symbolics?) constraints.

**Comment by bolognam** [comment]
@bgctw I have this same issue you're describing. I've tried a variety of different package versions (within the compat constraints) and I continue to get the same issue.

I don't have anything helpful to offer besides, "I understand what you're going through."

**Comment by mbolognaJH** [comment]
@bgctw it seems like my issues have been resolved by pinning PDEBase for now. Here's what is in my Project.toml compat:

`PDEBase = "=0.1.12"`

**Comment by bolognam** [comment]
@bgctw it seems like my issue has been solved by pinning PDEBase for now. Here's what is in my Project.toml compat:

`PDEBase = "=0.1.12"`

**Comment by ChrisRackauckas** [comment]
@sathvikbhagavan was there an issue due to your PDEBase release?

**Comment by sathvikbhagavan** [comment]
@bolognam, can I get an MWE for it? I think I know where it might be going wrong. Instead of

```julia
@named pdesys = PDESystem(.., [p1 => v1, p2 => v2])
```

try 

```julia
@named pdesys = PDESystem(.., [p1, p2]; defaults = Dict(p1 => v1, p2 => v2))
```

I think MOL also needs a release, try using master.

**Comment by ChrisRackauckas** [comment]
Are the tutorials and such updated to that? That should probably be listed as a breaking change for MethodOfLines.jl, though it's not for PDEBase since this was a non-standard use of the interface in MethodOfLines.jl that is being corrected.

**Comment by sathvikbhagavan** [comment]
No, I will update it.
